### PR TITLE
feat: export findProof()

### PR DESCRIPTION
**Pull request by raymondfeng**
We need to build an API to call deposit for bridged ERC20 tokens using
the lock transactin hash to find the proof and invoke NEAR deposit
function call.

Signed-off-by: Raymond Feng <enjoyjava@gmail.com>

### CODE REVIEW

**Review by mattlockyer — APPROVED** [review]
helps partner extend functionality

**Review by mfornet — APPROVED** [review]
LGTM

**Review by paouvrard — APPROVED** [review]
I'll keep this in mind for the upcoming new connector libraries also.

**Comment by raymondfeng** [comment]
Thanks for the quick action. Please publish a new release to npm for me to pick up and test.

**Comment by paouvrard** [comment]
@raymondfeng You can use this pre-release `"@near-eth/nep141-erc20": "1.3.4-2"` which contains the new findProof export.

**Pull request merged**
